project:
  type: website
  output-dir: docs

website:
  title: "Treinamento em análise de célula única"
  site-url: https://lint-edu.github.io/PPGBM0117.2025.1
  navbar:
    search: true
    left:
      - text: "Início"
        file: index.qmd
      - text: "Sobre"
        file: about.qmd
      - text: "Semana 1"
        menu:
          - text: "Coleta de Dados"
            file: material/semana1/01_data_collection.qmd
          - text: "Alinhamento"
            file: material/semana1/02_alignment.qmd
      - text: "Semana 2"
        menu:
          - text: "Controle de qualidade"
            file: material/semana2/03_quality_control.qmd
          - text: "Clusterização"
            file: material/semana2/04_clustering.qmd
      - text: "Semana 3"
        menu:
          - text: "Anotação de células I"
            file: material/semana3/05_cell_annotation.qmd
          - text: "Anotação de células II"
            file: material/semana3/06_cell_annotation.qmd
      - text: "Semana 4"
        menu:
          - text: "Integração de dados"
            file: material/semana4/07_data_integration.qmd

  page-footer:
    center: "Feito com ❤️ usando [Quarto](https://quarto.org)"

execute:
  freeze: auto  # re-render only when source changes

format:
  html:
    lightbox: true
    theme:
      - cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: false

knitr:
  opts_knit:
    root.dir: "/home/oandrefonseca/Disciplinas/PPGBM0117.2025.1"  