---
title: "Sobre a material"
format: html
---

# A Disciplina

Esta disciplina oferece uma introdução prática e conceitual à análise de dados de transcriptômica de célula única (single-cell RNA-seq), com foco em ferramentas computacionais modernas e aplicações em contextos biológicos diversos.

Ao longo do curso, os alunos terão contato com os principais pacotes da linguagem R para análise de dados de scRNA-seq, aprenderão sobre desenho experimental, controle de qualidade, análise de expressão gênica, integração de dados e inferência de trajetórias celulares.

O curso é estruturado em encontros teóricos e práticos, com foco na construção progressiva de um projeto aplicado com dados reais.


# O Professor

**André Fonseca** é professor visitante na Universidade Federal do Pará (UFPA) e atua na interface entre bioinformática, biologia molecular e ciência de dados.

Possui doutorado em Bioinformática (UFRN), com experiência em análise de dados ômicos, transcriptômica de célula única, caracterização de microambientes tumorais e desenvolvimento de pipelines reprodutíveis para análise de dados biomédicos. Também atuou como pesquisador em instituições como MD Anderson Cancer Center e Universidade de Houston.

Atualmente, coordena projetos voltados para a aplicação de inteligência artificial e bioinformática na caracterização funcional de células em tecidos humanos.

📫 Contato: [andrefonseca@ufpa.br](mailto:andrefonseca@ufpa.br)
